% parameter sweep for Dyson model CA6
% perturbed parameters around reference parameter set
% load results for plotting
% LJSchumacher 29.07.2013

clear all

% these parameters are not sweeped, but needed to calculate some reference
% values
cellRadius = 7.5;              % radius in um (= 7.5um)

% reference parameter set -- these should be the same as defautls in CA6.m
leadSpeed = 41.6;                     % speed of the leader cells in mu/h
followSpeed = 49.9;                 % speed of the follower cells in mu/h
numFilopodia = [2,2];  % the number of filopodia for lead cells and follower cells
filolength = cellRadius + 9*2;   % filopodial length (um) (measured from cell centre -- LJS). The average filopodial length found in experiment was 9mu, here I may be choosing a higher effective value to account for interfilopodial contact -- LJS
diffus = 1;%252e3;    % chemoattractant diffusivity (in (mu)^2/h?), for VEGF diffusing in the matrix this should probably be around 7e-11m^2/s = 252e3(mu)^2/h, for membrane bound VEGF unknown/near zero -- LJS
chi = 0.0001;                  % chemoattractant production term (usually 0.0001)
eatRate = 1;                      % chemoattractant consumption rate, usually 0.045 -- need to check this -- LJS
eatWidth = cellRadius;         % width of eating chemoattractant, equivalent to gaussian sigma
followerFraction = 0.7;        % proportion of cells that are followers (0<=follow_per<=1)

numRepeats = 10; % number of runs per parameter combination, to gather stats
numPerturbations = 21; % how many parameter combinations have been run altogether, not incl. repeats
numCells = NaN(numPerturbations,numRepeats);
saveInfo = cell(numPerturbations,1);

dateString = '2013_06_29'; % date of simulation that is to be loaded - needs to be adapted if ran on multiple days. Use wildcard (*) for time.

for ctr = 1:numRepeats
    
    % load results for reference set
    loadInfo = dir(['results/parameterSweeps/' dateString '*' ...
        '-leadSpeed_' num2str(leadSpeed) '_followSpeed_' num2str(followSpeed) ...
        '_nFiloLead_' num2str(numFilopodia(1)) '_nFiloFollow_' num2str(numFilopodia(2)) ...
        '_filolength_' num2str(filolength) '_diffus_' num2str(diffus) '_chi_' num2str(chi) ...
        '_eatRate_' num2str(eatRate) '_eatWidth_' num2str(eatWidth) '_followerFraction_' num2str(followerFraction) ...
        '_Run_' num2str(ctr) '.mat']);
    load(['results/parameterSweeps/' loadInfo.name], 'out');
    numCells(1,ctr) =  size(out.cells_save{end},2);
    if ctr == 1, saveInfo{1} = loadInfo.name; end
    
    % perturb parameters with experimental reference values
    perturbFactor = 1.1;
    
    for newLeadSpeed = [leadSpeed/perturbFactor, leadSpeed*perturbFactor]
        loadInfo = dir(['results/parameterSweeps/' dateString '*' ...
            '-leadSpeed_' num2str(newLeadSpeed) '_followSpeed_' num2str(followSpeed) ...
            '_nFiloLead_' num2str(numFilopodia(1)) '_nFiloFollow_' num2str(numFilopodia(2)) ...
            '_filolength_' num2str(filolength) '_diffus_' num2str(diffus) '_chi_' num2str(chi) ...
            '_eatRate_' num2str(eatRate) '_eatWidth_' num2str(eatWidth) '_followerFraction_' num2str(followerFraction) ...
            '_Run_' num2str(ctr) '.mat']);
        load(['results/parameterSweeps/' loadInfo.name], 'out');
        numCells(find(isnan(numCells(:,ctr)),1,'first'),ctr) =  size(out.cells_save{end},2);
        if ctr == 1, saveInfo{find(~isnan(numCells(:,ctr)),1,'last')} = loadInfo.name; end
    end
    
    for newFollowSpeed = [followSpeed/perturbFactor, followSpeed*perturbFactor]
        loadInfo = dir(['results/parameterSweeps/' dateString '*' ...
            '-leadSpeed_' num2str(newLeadSpeed) '_followSpeed_' num2str(newFollowSpeed) ...
            '_nFiloLead_' num2str(numFilopodia(1)) '_nFiloFollow_' num2str(numFilopodia(2)) ...
            '_filolength_' num2str(filolength) '_diffus_' num2str(diffus) '_chi_' num2str(chi) ...
            '_eatRate_' num2str(eatRate) '_eatWidth_' num2str(eatWidth) '_followerFraction_' num2str(followerFraction) ...
            '_Run_' num2str(ctr) '.mat']);
        load(['results/parameterSweeps/' loadInfo.name], 'out');
        numCells(find(isnan(numCells(:,ctr)),1,'first'),ctr) =  size(out.cells_save{end},2);
        if ctr == 1, saveInfo{find(~isnan(numCells(:,ctr)),1,'last')} = loadInfo.name; end
    end
    
    for newnumFilopodia = [[3; 2], [2; 1], [1; 1], [3; 3]]
        loadInfo = dir(['results/parameterSweeps/' dateString '*' ...
            '-leadSpeed_' num2str(newLeadSpeed) '_followSpeed_' num2str(followSpeed) ...
            '_nFiloLead_' num2str(newnumFilopodia(1)) '_nFiloFollow_' num2str(newnumFilopodia(2)) ...
            '_filolength_' num2str(filolength) '_diffus_' num2str(diffus) '_chi_' num2str(chi) ...
            '_eatRate_' num2str(eatRate) '_eatWidth_' num2str(eatWidth) '_followerFraction_' num2str(followerFraction) ...
            '_Run_' num2str(ctr) '.mat']);
        load(['results/parameterSweeps/' loadInfo.name], 'out');
        numCells(find(isnan(numCells(:,ctr)),1,'first'),ctr) =  size(out.cells_save{end},2);
        if ctr == 1, saveInfo{find(~isnan(numCells(:,ctr)),1,'last')} = loadInfo.name; end
    end
    
    for newFilolength = [filolength/perturbFactor, filolength*perturbFactor]
        loadInfo = dir(['results/parameterSweeps/' dateString '*' ...
            '-leadSpeed_' num2str(newLeadSpeed) '_followSpeed_' num2str(followSpeed) ...
            '_nFiloLead_' num2str(numFilopodia(1)) '_nFiloFollow_' num2str(numFilopodia(2)) ...
            '_filolength_' num2str(newFilolength) '_diffus_' num2str(diffus) '_chi_' num2str(chi) ...
            '_eatRate_' num2str(eatRate) '_eatWidth_' num2str(eatWidth) '_followerFraction_' num2str(followerFraction) ...
            '_Run_' num2str(ctr) '.mat']);
        load(['results/parameterSweeps/' loadInfo.name], 'out');
        numCells(find(isnan(numCells(:,ctr)),1,'first'),ctr) =  size(out.cells_save{end},2);
        if ctr == 1, saveInfo{find(~isnan(numCells(:,ctr)),1,'last')} = loadInfo.name; end
    end
    
    for newFollowerFraction = [followerFraction/perturbFactor, followerFraction*perturbFactor]
        loadInfo = dir(['results/parameterSweeps/' dateString '*' ...
            '-leadSpeed_' num2str(newLeadSpeed) '_followSpeed_' num2str(followSpeed) ...
            '_nFiloLead_' num2str(numFilopodia(1)) '_nFiloFollow_' num2str(numFilopodia(2)) ...
            '_filolength_' num2str(filolength) '_diffus_' num2str(diffus) '_chi_' num2str(chi) ...
            '_eatRate_' num2str(eatRate) '_eatWidth_' num2str(eatWidth) '_followerFraction_' num2str(newFollowerFraction) ...
            '_Run_' num2str(ctr) '.mat']);
        load(['results/parameterSweeps/' loadInfo.name], 'out');
        numCells(find(isnan(numCells(:,ctr)),1,'first'),ctr) =  size(out.cells_save{end},2);
        if ctr == 1, saveInfo{find(~isnan(numCells(:,ctr)),1,'last')} = loadInfo.name; end
    end
    
    % perturb parameters without experimental reference values
    perturbFactor = 10;
    
    for newDiffus = [diffus/perturbFactor, diffus*perturbFactor]
        loadInfo = dir(['results/parameterSweeps/' dateString '*' ...
            '-leadSpeed_' num2str(newLeadSpeed) '_followSpeed_' num2str(followSpeed) ...
            '_nFiloLead_' num2str(numFilopodia(1)) '_nFiloFollow_' num2str(numFilopodia(2)) ...
            '_filolength_' num2str(filolength) '_diffus_' num2str(newDiffus) '_chi_' num2str(chi) ...
            '_eatRate_' num2str(eatRate) '_eatWidth_' num2str(eatWidth) '_followerFraction_' num2str(followerFraction) ...
            '_Run_' num2str(ctr) '.mat']);
        load(['results/parameterSweeps/' loadInfo.name], 'out');
        numCells(find(isnan(numCells(:,ctr)),1,'first'),ctr) =  size(out.cells_save{end},2);
        if ctr == 1, saveInfo{find(~isnan(numCells(:,ctr)),1,'last')} = loadInfo.name; end
    end
    
    for newChi = [chi/perturbFactor, chi*perturbFactor]
        loadInfo = dir(['results/parameterSweeps/' dateString '*' ...
            '-leadSpeed_' num2str(newLeadSpeed) '_followSpeed_' num2str(followSpeed) ...
            '_nFiloLead_' num2str(numFilopodia(1)) '_nFiloFollow_' num2str(numFilopodia(2)) ...
            '_filolength_' num2str(filolength) '_diffus_' num2str(diffus) '_chi_' num2str(newChi) ...
            '_eatRate_' num2str(eatRate) '_eatWidth_' num2str(eatWidth) '_followerFraction_' num2str(followerFraction) ...
            '_Run_' num2str(ctr) '.mat']);
        load(['results/parameterSweeps/' loadInfo.name], 'out');
        numCells(find(isnan(numCells(:,ctr)),1,'first'),ctr) =  size(out.cells_save{end},2);
        if ctr == 1, saveInfo{find(~isnan(numCells(:,ctr)),1,'last')} = loadInfo.name; end
    end
    
    for newEatRate = [eatRate/perturbFactor, eatRate*perturbFactor]
        loadInfo = dir(['results/parameterSweeps/' dateString '*' ...
            '-leadSpeed_' num2str(newLeadSpeed) '_followSpeed_' num2str(followSpeed) ...
            '_nFiloLead_' num2str(numFilopodia(1)) '_nFiloFollow_' num2str(numFilopodia(2)) ...
            '_filolength_' num2str(filolength) '_diffus_' num2str(diffus) '_chi_' num2str(chi) ...
            '_eatRate_' num2str(newEatRate) '_eatWidth_' num2str(eatWidth) '_followerFraction_' num2str(followerFraction) ...
            '_Run_' num2str(ctr) '.mat']);
        load(['results/parameterSweeps/' loadInfo.name], 'out');
        numCells(find(isnan(numCells(:,ctr)),1,'first'),ctr) =  size(out.cells_save{end},2);
        if ctr == 1, saveInfo{find(~isnan(numCells(:,ctr)),1,'last')} = loadInfo.name; end
    end
    
    perturbFactor = 2;
    for newEatWidth = [eatWidth/perturbFactor, eatWidth*perturbFactor]
        loadInfo = dir(['results/parameterSweeps/' dateString '*' ...
            '-leadSpeed_' num2str(newLeadSpeed) '_followSpeed_' num2str(followSpeed) ...
            '_nFiloLead_' num2str(numFilopodia(1)) '_nFiloFollow_' num2str(numFilopodia(2)) ...
            '_filolength_' num2str(filolength) '_diffus_' num2str(diffus) '_chi_' num2str(chi) ...
            '_eatRate_' num2str(eatRate) '_eatWidth_' num2str(newEatWidth) '_followerFraction_' num2str(followerFraction) ...
            '_Run_' num2str(ctr) '.mat']);
        load(['results/parameterSweeps/' loadInfo.name], 'out');
        numCells(find(isnan(numCells(:,ctr)),1,'first'),ctr) =  size(out.cells_save{end},2);
        if ctr == 1, saveInfo{find(~isnan(numCells(:,ctr)),1,'last')} = loadInfo.name; end
    end
    
end
save(['results/parameterSweeps/' dateString '-collatedResults'], 'numCells', 'saveInfo')
