% plot leader follower switching traces for selected cells
% LJS -- 27.09.15
load('results/experiment31conversion4/exp31_conversion_4_defaultFollow_2_numSteps_8_4_sensingAcc_0.1_Run_1.mat')
load_results
plot(happiness(1:60,1:2:12))
xlabel('time (min)')
set(gca,'ytick',[0 1],'yticklabel',{'follower','leader'})

%% export figure
exportOptions = struct('Format','eps2',...
    'Width','17.0',...
    'Height','7.0',...
    'Color','rgb',...
    'Resolution',300,...
    'FontMode','fixed',...
    'FontSize',10,...
    'LineWidth',2);

pos = get(gcf,'Position');
set(gcf,'PaperUnits','centimeters','Position',pos,'color','none');
filename = ['../../Thesis/figures/leaderFollowerSwitchingTraces'];
exportfig(gcf,[filename '.eps'],exportOptions);
system(['epstopdf ' filename '.eps']);