require(BHC)
setwd("~/Dropbox/DPhil/DysonModel/all_vers2/integrateAndSwitch/")
geneNames <- read.csv("cleanGenes.csv")
timePoints <- c(0,2,4,8,16,30,45,60,90,92,94,98,106,120,135,150,180)

offData = read.csv("meanOffExpression.csv")
offDataMat <- data.matrix(offData[,2:10])
offError = read.csv("offError.csv")
hcOff <- bhc(offDataMat, geneNames[,1], 0, timePoints[1:9], "time-course", noise=offError[,1], numReps=1, noiseMode=2, numThreads=1, verbose=TRUE)
WriteOutClusterLabels(hcOff, "bhcOffLabels.txt", verbose=TRUE)
plot(hcOff, axes=FALSE)

onData = read.csv("meanOnExpression.csv")
onDataMat <- data.matrix(onData[,2:10])
onError = read.csv("onError.csv")
hcOn <- bhc(onDataMat, geneNames[,1], 0, timePoints[9:17], "time-course", noise=offError[,1], numReps=1, noiseMode=2, numThreads=1, verbose=TRUE)
WriteOutClusterLabels(hcOn, "bhcOnLabels.txt", verbose=TRUE)
plot(hcOn, axes=FALSE)

allData = read.csv("meanExpression.csv")
allDataMat <- data.matrix(allData[,3:19])
meanError = read.csv("meanError.csv")
hcAll <- bhc(allDataMat, geneNames[,1], 0, timePoints, "time-course", noise=meanError[,1], numReps=1, noiseMode=2, numThreads=1, verbose=TRUE)
WriteOutClusterLabels(hcAll, "bhcAllLabels.txt", verbose=TRUE)
plot(hcAll, axes=FALSE)